---
title: "CIre within analysis"
output:
  pdf_document: default
  html_document: default
---

# Load packages
```{r}
pacman::p_load(readr, lme4, emmeans, sjPlot, stargazer)
```

# Load data
```{r}
long = read_csv("long.csv")

long$Deviant=as.factor(long$Deviant)
long$DeviantLevel=as.factor(long$DeviantLevel)
long$Time = as.factor(long$Time)
long$ID=as.factor(long$ID)
long$M_knowledge = ordered(long$M_knowledge, levels = c("1","2","3","4","5"))
long$M_enjoyment=ordered(long$M_enjoyment, levels = c("1", "2", "3", "4", "5", "6","7"))
long$Listeninghabits=ordered(long$Listeninghabits, levels = c("Low", "High"))

change_all = read_csv("change_all.csv")
change_all$Deviant=as.factor(change_all$Deviant)
change_all$DeviantLevel=as.factor(change_all$DeviantLevel)
change_all$ID=as.factor(change_all$ID)
```

# Hierarchical mixed effects modeling - MMN Amplitude
```{r}
M0=lmer(Amplitude~1+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M1=lmer(Amplitude~Deviant+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M2=lmer(Amplitude~Deviant+DeviantLevel+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M3=lmer(Amplitude~Deviant+DeviantLevel+Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M4=lmer(Amplitude~Deviant*DeviantLevel+Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M5=lmer(Amplitude~Deviant*DeviantLevel+Deviant*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M5_0 = lmer(Amplitude~Deviant*DeviantLevel+Deviant*Time+0+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M6=lmer(Amplitude~Deviant*DeviantLevel+Deviant*Time+DeviantLevel*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M7=lmer(Amplitude~Deviant*DeviantLevel*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

anova = anova(M0,M1,M2,M3,M4,M5,M6,M7)
anova

#export model output to word table
 tab_df(anova,
        alternate.rows = TRUE,
        title = "Effect on MMN Amplitude",
        file = "amp_within.doc")
```

## Best model
```{r}
summary(M5)

#Checking assumptions with diagnostic plots
qqnorm(resid(M5))
plot(M5)
```

## Post-hoc analysis
```{r}
# 
# emm_options(lmerTest.limit = 10854)
# 
# emm_options(disable.pbkrtest = TRUE)


emm_r <- emmeans(M5, pairwise ~ Time)
emm_rc <- emm_r[[2]]

emm_d <- emmeans(M5, pairwise ~ Deviant)
emm_dc <- emm_d[[2]]

#Time by deviant interaction

emm_r.d <- emmeans(M5, pairwise ~ Time | Deviant)
IC_r.d <- contrast(emm_r.d[[1]], method = "pairwise")

emm_d.r <- emmeans(M5, pairwise ~ Deviant | Time)
IC_d.r <- contrast(emm_d.r[[1]], method = "pairwise")

# rbind(emm_rc, emm_dc, IC_r.d[1:4], IC_d.r[1:12], adjust = "mvt")
# rbind(IC_r.d[1:4], adjust = "mvt")
# rbind(IC_r.d[1:4], adjust = "none")
rbind(IC_r.d[c(1,2,3, 4)], adjust = "none")
# IC_r.d[1:4]
# IC_d.r[1:12]
confint(rbind(IC_r.d[c(1,2,3,4)],  adjust = 'none'))

# IC_d.r[c(1,3,7,9)]

IC_IC_d.r <- contrast(emm_d.r[[1]], interaction = c("pairwise", "consec"), by = NULL)
rbind(IC_IC_d.r[1:6], adjust = "none")

confint(rbind(IC_IC_d.r[1:6]), adjust ="none")
```

# Hierarchical mixed effects modeling - 3-AFC (Behavioral)
```{r}
M0=glmer(cbind(AvCor*6,6)~1+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M1=glmer(cbind(AvCor*6,6)~Deviant+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M2=glmer(cbind(AvCor*6,6)~Deviant+DeviantLevel+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M3=glmer(cbind(AvCor*6,6)~Deviant+DeviantLevel+Time+(1|ID), data=long,family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M4=glmer(cbind(AvCor*6,6)~Deviant*DeviantLevel+Time+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M5=glmer(cbind(AvCor*6,6)~Deviant*DeviantLevel+Deviant*Time+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M6=glmer(cbind(AvCor*6,6)~Deviant*DeviantLevel+Deviant*Time+DeviantLevel*Time+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M7=glmer(cbind(AvCor*6,6)~Deviant*DeviantLevel*Time+(1|ID), data=long, family="binomial", control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

anova = anova(M0,M1,M2,M3,M4,M5,M6, M7)
anova

#export model output to word table
 tab_df(anova,
        alternate.rows = TRUE,
        title = "Effect on behavioral hit rates",
        file = "behav_within.doc")
```

## Best model
```{r}
summary(M2)
```

# Hierarchical mixed effects modeling - Latency
```{r}
M0=lmer(Latency_peak~1+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M1=lmer(Latency_peak~Deviant+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M2=lmer(Latency_peak~Deviant+DeviantLevel+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M3=lmer(Latency_peak~Deviant+DeviantLevel+Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M4=lmer(Latency_peak~Deviant*DeviantLevel+Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M5=lmer(Latency_peak~Deviant*DeviantLevel+Deviant*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M6=lmer(Latency_peak~Deviant*DeviantLevel+Deviant*Time+DeviantLevel*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

M7=lmer(Latency_peak~Deviant*DeviantLevel*Time+(1|ID), data=long, REML = FALSE, control = lmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))


anova = anova(M0,M1,M2,M3,M4,M5,M6, M7)
anova

#export model output to word table
 tab_df(anova,
        alternate.rows = TRUE,
        title = "Effect on MMN Latency",
        file = "lat_within.doc")
```
